import type { SubtitleOption } from '../VideoSourceProvider';

export interface YoutubeCaptionTrack extends SubtitleOption {
  baseUrl: string;
  languageCode: string;
  isAutoGenerated?: boolean;
  isTranslatable?: boolean;
  translatedFrom?: string;
}

export interface YoutubePlayerResponse {
  videoDetails?: {
    videoId?: string;
    title?: string;
    author?: string;
    shortDescription?: string;
    lengthSeconds?: string;
    thumbnail?: {
      thumbnails?: Array<{ url?: string; width?: number; height?: number }>;
    };
  };
  microformat?: {
    playerMicroformatRenderer?: {
      publishDate?: string;
      uploadDate?: string;
      ownerChannelName?: string;
      description?: {
        simpleText?: string;
      };
    };
  };
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: Array<{
        baseUrl?: string;
        languageCode?: string;
        kind?: string;
        name?: {
          simpleText?: string;
          runs?: Array<{ text?: string }>;
        };
        isTranslatable?: boolean;
      }>;
    };
  };
}
