import type { LocalConfig } from '../../store/types';
import type { VideoInfo } from '../VideoSourceProvider';
import { getYoutubeVideoFromOfficialApi } from './officialApi';
import type { YoutubeCaptionTrack, YoutubePlayerResponse } from './types';

export interface ParsedYoutubePlayerResponse {
  video: VideoInfo;
  tracks: YoutubeCaptionTrack[];
}

export async function getYoutubeVideoInfo(config?: LocalConfig): Promise<VideoInfo> {
  const parsed = parseYoutubePlayerResponse(readYoutubePlayerResponse(), location.href);
  if (parsed.video.sourceId) return parsed.video;

  const videoId = extractYoutubeVideoId(location.href);
  if (!videoId) throw new Error('无法从当前页面识别 YouTube 视频 ID');
  const official = await getYoutubeVideoFromOfficialApi(videoId, config);
  if (official) return official;
  throw new Error('无法读取 YouTube 视频信息');
}

export function parseYoutubePlayerResponse(raw: unknown, pageUrl: string): ParsedYoutubePlayerResponse {
  const response = (raw ?? {}) as YoutubePlayerResponse;
  const videoId = response.videoDetails?.videoId ?? extractYoutubeVideoId(pageUrl) ?? '';
  const meta = response.microformat?.playerMicroformatRenderer;
  const title = response.videoDetails?.title ?? readMetaContent('meta[property="og:title"]') ?? readDocumentTitle();
  const creatorName = response.videoDetails?.author ?? meta?.ownerChannelName;
  const thumbnails = response.videoDetails?.thumbnail?.thumbnails ?? [];
  const coverUrl = thumbnails[thumbnails.length - 1]?.url ?? readMetaContent('meta[property="og:image"]');
  const description =
    response.videoDetails?.shortDescription ?? meta?.description?.simpleText ?? readMetaContent('meta[name="description"]');
  const publishedAt = parsePublishedAt(meta?.publishDate ?? meta?.uploadDate);
  const url = canonicalUrl() ?? normalizedYoutubeUrl(videoId, pageUrl);

  return {
    video: {
      source: 'youtube',
      sourceId: videoId,
      platform: 'YouTube',
      title,
      creatorName,
      upName: creatorName,
      description,
      duration: parseDurationSeconds(response.videoDetails?.lengthSeconds),
      coverUrl,
      publishedAt,
      stats: countValue(response.videoDetails?.viewCount) === undefined
        ? undefined
        : { views: countValue(response.videoDetails?.viewCount) },
      url,
    },
    tracks: parseYoutubeCaptionTracks(response),
  };
}

function countValue(value: unknown): number | undefined {
  const count = Number(value);
  return Number.isFinite(count) && count >= 0 ? count : undefined;
}

export function parseYoutubeCaptionTracks(response: YoutubePlayerResponse): YoutubeCaptionTrack[] {
  const tracks = response.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
  return tracks
    .filter((track) => track.baseUrl && track.languageCode)
    .map((track) => {
      const languageCode = track.languageCode!;
      const label = labelText(track.name) || languageCode;
      const isAutoGenerated = track.kind === 'asr';
      return {
        id: languageCode,
        label: `${label}${isAutoGenerated ? ' (auto)' : ''}`,
        baseUrl: track.baseUrl!,
        languageCode,
        isAutoGenerated,
        isTranslatable: track.isTranslatable,
      };
    });
}

export function readYoutubePlayerResponse(): YoutubePlayerResponse | undefined {
  if (typeof window === 'undefined' || typeof document === 'undefined') return undefined;
  const pageUrl = typeof location === 'undefined' ? '' : location.href;
  const candidates: YoutubePlayerResponse[] = [];
  const direct = (window as any).ytInitialPlayerResponse;
  if (direct) candidates.push(direct);
  candidates.push(...readYoutubePlayerResponsesFromText(Array.from(document.scripts).map((script) => script.textContent ?? '').join('\n')));
  return selectBestYoutubePlayerResponse(candidates, pageUrl);
}

export function readYoutubePlayerResponseFromHtml(html: string, pageUrl: string): YoutubePlayerResponse | undefined {
  return selectBestYoutubePlayerResponse(readYoutubePlayerResponsesFromText(html), pageUrl);
}

function readYoutubePlayerResponsesFromText(text: string): YoutubePlayerResponse[] {
  const responses: YoutubePlayerResponse[] = [];
  let offset = 0;
  while (offset < text.length) {
    const index = text.indexOf('ytInitialPlayerResponse', offset);
    if (index < 0) break;
    const json = extractAssignedJson(text.slice(index));
    if (json) responses.push(json as YoutubePlayerResponse);
    offset = index + 'ytInitialPlayerResponse'.length;
  }
  return responses;
}

function selectBestYoutubePlayerResponse(
  candidates: YoutubePlayerResponse[],
  pageUrl: string,
): YoutubePlayerResponse | undefined {
  const videoId = extractYoutubeVideoId(pageUrl);
  const matching = videoId
    ? candidates.filter((candidate) => candidate.videoDetails?.videoId === videoId)
    : candidates;
  const pool = matching.length ? matching : candidates;
  return (
    pool.find((candidate) => parseYoutubeCaptionTracks(candidate).length > 0) ??
    pool[0]
  );
}

export function extractYoutubeVideoId(url: string): string | undefined {
  try {
    const parsed = new URL(url);
    if (!/(^|\.)youtube\.com$/.test(parsed.hostname)) return undefined;
    if (parsed.pathname === '/watch') return parsed.searchParams.get('v') ?? undefined;
    const shorts = parsed.pathname.match(/^\/shorts\/([^/?#]+)/);
    return shorts?.[1];
  } catch {
    return undefined;
  }
}

function extractAssignedJson(input: string): unknown {
  const equals = input.indexOf('=');
  if (equals < 0) return undefined;
  const start = input.indexOf('{', equals);
  if (start < 0) return undefined;
  let depth = 0;
  let inString = false;
  let escaped = false;
  for (let index = start; index < input.length; index += 1) {
    const char = input[index];
    if (inString) {
      if (escaped) escaped = false;
      else if (char === '\\') escaped = true;
      else if (char === '"') inString = false;
      continue;
    }
    if (char === '"') inString = true;
    else if (char === '{') depth += 1;
    else if (char === '}') {
      depth -= 1;
      if (depth === 0) {
        try {
          return JSON.parse(input.slice(start, index + 1));
        } catch {
          return undefined;
        }
      }
    }
  }
  return undefined;
}

type YoutubeCaptionTrackName = {
  simpleText?: string;
  runs?: Array<{ text?: string }>;
};

function labelText(name: YoutubeCaptionTrackName | undefined): string {
  return name?.simpleText ?? name?.runs?.map((run) => run.text ?? '').join('') ?? '';
}

function parseDurationSeconds(value: string | undefined): number | undefined {
  const seconds = Number(value);
  return Number.isFinite(seconds) && seconds > 0 ? seconds : undefined;
}

function parsePublishedAt(value: string | undefined): number | undefined {
  if (!value) return undefined;
  const time = Date.parse(value);
  return Number.isFinite(time) ? Math.floor(time / 1000) : undefined;
}

function readMetaContent(selector: string): string | undefined {
  if (typeof document === 'undefined') return undefined;
  return document.querySelector<HTMLMetaElement>(selector)?.content || undefined;
}

function readDocumentTitle(): string {
  return typeof document === 'undefined' ? '' : document.title.replace(/ - YouTube$/, '');
}

function canonicalUrl(): string | undefined {
  if (typeof document === 'undefined') return undefined;
  return document.querySelector<HTMLLinkElement>('link[rel="canonical"]')?.href || undefined;
}

function normalizedYoutubeUrl(videoId: string, fallback: string): string {
  return videoId ? `https://www.youtube.com/watch?v=${videoId}` : fallback;
}
